sudo: required
services:
  - docker
before_install:
  - docker build -t sheffdocker/docker-app-react -f Dockerfile.dev .
script:
  - docker run sheffdocker/docker-app-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-app-react
  env: DockerAppReact-env
  bucket_name: elasticbeanstalk-us-west-2-172886367576
  bucket_path: docker-app-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
