sudo: required
services:
  - docker
before_install:
  - docker build -t sheffdocker/docker-app-react -f Dockerfile.dev .
script:
  - docker run sheffdocker/docker-app-react npm run test -- --coverage
